Deprecate sweep synthesis
pyfar/pyfar pull request #201
Opened 2021-06-15 11:13 UTC by f-brinkmann

### Which issue(s) are closed by this pull request?

As discussed during the weekly

### Changes proposed in this pull request:

- deprecate `pyfar.signals.linear_sweep` in favor of `pyfar.signals.linear_sweep_time`
- deprecate `pyfar.signals.exponential_sweep` in favor of `pyfar.signals.exponential_sweep_time`
- rename tests and add tests for deprecation

2021-06-17 04:15 UTC, sikersten approved these changes

2021-06-18 08:05 UTC, mberz requested changes
One minor thing: Let's replace the UserWarning with PendingDeprecationWarning

2021-06-18 08:05 UTC, mberz commented on pyfar/signals/deterministic.py
> +                   "of pyfar.signals.linear_sweep_time."))
Let's use the respective type here :)

2021-06-18 08:05 UTC, mberz commented on pyfar/signals/deterministic.py
> +                   "of pyfar.signals.exponential_sweep_time."))
```suggestion
    warnings.warn(("This function will be deprecated in pyfar 0.5.0 in favor "
                   "of pyfar.signals.exponential_sweep_time."), PendingDeprecationWarning)
```

2021-06-18 08:05 UTC, mberz commented on tests/test_signals.py
> +    with pytest.warns(UserWarning, match="This function will be deprecated"):
```suggestion
    with pytest.warns(PendingDeprecationWarning, match="This function will be deprecated"):
```

2021-06-18 08:05 UTC, mberz commented on tests/test_signals.py
> +    with pytest.warns(UserWarning, match="This function will be deprecated"):
```suggestion
    with pytest.warns(PendingDeprecationWarning, match="This function will be deprecated"):
```

2021-06-18 10:34 UTC, mberz approved these changes

2021-06-18 11:33 UTC, merged