Feature/3d remaining plots
pyfar/pyfar pull request #276
Opened 2022-02-10 08:52 UTC by f-brinkmann

### Which issue(s) are closed by this pull request?

Add remaining 2D Plots

### Changes proposed in this pull request:

- Add `freq2d`, `phase2d`, `group_delay2d`, `time_freq2d`, `freq_phase2d`, `freq_groupd_delay2d`
- Change custom shading from `gouraud` to `nearest`. The old default seemed a bit deceiving for me, as it might make data look more smooth / high res. than they actually are (https://matplotlib.org/devdocs/gallery/images_contours_and_fields/pcolormesh_grids.html)
- Add new functionality to the interaction module to account for correct handling of axis operations (move, zoom, log/lin) after changing the orientation of 2D plots
- separate handling of `kwargs` (keyword arguments) for different plotfunctions (`matplotlib.pyplot.plot`, `matplotlib.pyplot.pcolormesh`)

### Things left for the next pull-request

- Add more testing (easier if all functions are there)
- Reduce code redundancy (easier if all functions are there)

2022-02-11 08:17 UTC, sikersten requested changes
Many thanks for implementing! Plots look very nice and interaction works smoothly :)
Some general comments we can discuss:

- I'm not completely happy with the default name _Points_ for the second axis. What about something like _Index_? For specific values, one needs to add a specific label anyway.
- I'd suggest to change the functions' suffix to `_2d` instead of `2d`. In my opinion, it matches the underscore convention (e.g., in `freq_phase`) better by clearly separating it from the last phrase.
- In my case the frequency ticker only showed 1k and 10k when plotting the examples from the functions. I'd suggest to have the same as for `freq`. The difference is nicely illustrated when toggling between `freq2d` and `freq` :)

2022-02-11 08:17 UTC, sikersten commented on pyfar/plot/two_d.py
> +        >>> pf.plot.time2d(signal)
```suggestion
        >>> pf.plot.time_freq2d(signal)
```

2022-02-11 08:17 UTC, sikersten commented on pyfar/plot/two_d.py
> +        >>> pf.plot.time2d(signal)
```suggestion
        >>> pf.plot.freq_phase2d(signal)
```

2022-02-11 08:17 UTC, sikersten commented on pyfar/plot/two_d.py
> +        >>> pf.plot.time2d(signal)
```suggestion
        >>> pf.plot.freq_group_delay2d(signal)
```

2022-02-12 13:00 UTC, f-brinkmann commented
@sikersten : all suggestions implemented :)

2022-02-25 08:02 UTC, sikersten approved these changes

2022-02-25 12:13 UTC, merged