Feature/average function
pyfar/pyfar pull request #330
Opened 2022-07-20 11:56 UTC by twennemann

New Branche for average function.

Tests will come soon

2022-07-21 16:31 UTC, f-brinkmann requested changes
Thanks for opening this - found a few minor things and a few things to discuss in the weekly

2022-07-21 16:31 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +        raise TypeError('Input data has to be of type: Signal')
can now use TimeData and FrequencyData depending on the mode

2022-07-21 16:31 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +        weights = weights/np.sum(weights)
If we allow weights that can be broadcasted to cshape, we should not do the normalization. And add a note to the docstring that weights usually sum to 1 for most applications. Instead we could test if they can be braodcasted and raise a ValueError if not...

2022-07-21 16:31 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +        data = np.abs(signal.freq.copy())**2
copy() operation not needed - np.abs does it for us.

2022-07-21 16:31 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +            mode == 'complex' or mode == 'magnitude'):
shorter
```suggestion
    if mode in ['time', 'complex', 'magnitude']:
```

2022-07-21 16:31 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +        data = np.sum(data, axis=axis, keepdims=True)
- The sum is done in any case and could go before the if, else.
- I would suggest to make keepdims a parameter with the default being False. In that case, we would add ´np.squeeze(data, axis)` after the sum (where we keep keepdims)

2022-07-21 16:31 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +def average(signal, mode='time', axis=None, phase_copy=None,
docstring and checks for axis are missing. We have to make sure that `np.max(axis) <= len(signal.cshape)`

2022-09-19 16:06 UTC, mberz requested changes
This PR is marked as requirement for the next release, but looks unfinished. 
What's the status on this? I'd suggest moving this to the next release.

2022-09-19 16:06 UTC, mberz commented on pyfar/dsp/dsp.py
> +                weights /= signal.cshape[idx]
Can't we do this without a loop?

2022-09-19 16:06 UTC, mberz commented on pyfar/dsp/dsp.py
> +               np.exp(1j*pyfar.dsp.phase(signal, unwrap=True))
This is the exact same as `mode='complex'`

2022-09-19 16:06 UTC, mberz commented on pyfar/dsp/dsp.py
> +    data = np.sum(data, axis=axis, keepdims=keepdims)
You can also use np.average, which supports weighted averaging. 
https://numpy.org/doc/stable/reference/generated/numpy.average.html
This way you can also avoid the looped version of calculating the weights.

2022-10-02 12:37 UTC, f-brinkmann approved these changes

2022-10-04 09:05 UTC, mberz requested changes
1. There's a couple of things in the docstring which require fixes.
2. Please don't copy the entire input signal only to create a new Signal, TimeData or Freq.Data

2022-10-04 09:48 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +        ``signal.cshape`` to avoid averaging across the time or frequency axis.
Good point, this is too short at the moment. I would suggest to postpone this until we change the parameter name to `caxis`. That will add content to the concepts that could be well written and linked from here.

2022-10-05 07:28 UTC, sikersten commented on pyfar/dsp/dsp.py
> +            data is not aligned across channels.
```suggestion
            Average ``signal.time`` if the signal is in the time domain and
            ``signal.freq`` if the signal is in the frequency domain. Note that
            these operations are equivalent for `Signal` objects due to the
            linearity of the averaging and the FFT. This mode might cause
            artifacts if the data is not aligned across channels.
```

2022-10-05 07:28 UTC, sikersten commented on pyfar/dsp/dsp.py
> +            average the magnitude spectra and the unwrapped phase seperatly.
```suggestion
            Average the magnitude spectra and the unwrapped phase separately.
```

2022-10-05 07:29 UTC, sikersten commented on pyfar/dsp/dsp.py
> +            reversed before returning the averaged signal.
```suggestion
            Average the logarithmic magnitude spectra
            using :py:func:`~pyfar.dsp.decibel` and discard the phase. The
            logarithm is reversed before returning the averaged signal.
```

2022-10-05 07:29 UTC, sikersten commented on pyfar/dsp/dsp.py
> +    Returns
```suggestion
    
    Returns
```

2022-10-05 07:29 UTC, sikersten commented on pyfar/dsp/dsp.py
> +        averaged input Signal
```suggestion
        Averaged input Signal.
```

2022-10-05 07:31 UTC, sikersten commented on pyfar/dsp/dsp.py
> +
```suggestion
    :py:func:`~pyfar.dsp.minimum_phase` can be used to obtain a phase for
    magnitude spectra after using a mode that discards the phase.
```

2022-10-05 11:28 UTC, sikersten approved these changes

2022-10-05 11:53 UTC, merged