Use emtpy string for empty comments
pyfar/pyfar pull request #379
Opened 2022-11-04 16:17 UTC by twennemann

- Changed the initialization of comments from "none" to and empty string "".
- revised the tests.
- comments which are not of type string will no longer be casted. A TypeError will be raised instead.

2022-11-10 16:59 UTC, f-brinkmann requested changes
Thanks, looks good to me - only the documentation fails on circle and needs fixing. Do you want help with that?

2022-11-11 06:39 UTC, sikersten requested changes
Look good thanks! Please remove code that is not related to this PR, otherwise approved :)

2022-11-11 06:39 UTC, sikersten commented on examples/pyfar_demo.ipynb
> +   "display_name": "Python 3.10.4 ('pyfar')",
please remove these not related changes from the PR :)

2022-11-11 06:39 UTC, sikersten commented on tests/test_dsp_average.py
> +    [pf.FrequencyData([[0.01, 0.1, ], [1, 10]], [1, 2]),
It looks like these changes are not related to the PR? Please move to a separate one :)

2022-11-11 06:44 UTC, sikersten commented on pyfar/classes/audio.py
> +.
This should fix the documentation build (empty line instead of full stop)
```suggestion

```

2022-11-11 07:12 UTC, sikersten commented
Closes issue #359

2022-11-16 13:04 UTC, f-brinkmann approved these changes

2022-11-18 08:52 UTC, sikersten approved these changes

2022-11-18 12:15 UTC, merged