Accept Nans in Normalize
pyfar/pyfar pull request #399
Opened 2022-12-01 16:23 UTC by twennemann

We decided
- We allow NaNs in normalize
- We list all DSP functions taking Time/FrequencyData and check if they can allow NaNs
- We will check if there are any functions that should allow for Time/FrequencyData but dont

2022-12-04 12:43 UTC, f-brinkmann commented
Thanks for the effort. The code looks good. But I wonder if we should discuss this in more detail. Which functions should allow NaNs? Should there be a flag, that has to be set or should it be allowed by default? Is there a good way of testing this for all functions that allow it?

2022-12-08 09:02 UTC, ahms5 reviewed
looks good to me, I think we should add that nans are ignored in the doc.

2022-12-09 12:40 UTC, f-brinkmann commented
We discuss that we explicitly want to add an `ignore_nan` flag to the functions that except time data and NaNs would be a problem. This is also relevant for `dsp.average`.

2022-12-16 13:25 UTC, mberz commented
This is an example of the naming convention scipy follows:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pmean.html#scipy.stats.pmean

2023-01-11 11:00 UTC, twennemann commented
Added `nan_policy` parameter to normalize function. It follows scipys naming convention. 
Use:
- `propagate` --> Output will be NaN if Signal includes NaNs (with np.max/np.mean)
- `omit` --> NaNs will be omitted in the normalization (with np.nanmax/np.nanmean)
- `raise`--> A `ValueError` will be raised if the signal includes NaNs

I thought `nan_policy='raise'` might be a logical default, so the user will be informed that the signal includes NaNs and to choose a policy.

2023-01-11 15:27 UTC, f-brinkmann requested changes
Looks good to me. I had only one minor comment and question.

2023-01-11 15:27 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +              unit=None, nan_policy='raise', return_reference=False):
I think the new parameter should go last to maintain backwards compatability

2023-01-11 15:27 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +                                axis=-1)
Why not directly use `np.nanmax(..., nan_policy=nan_policy)`?
Might also be changed in the elif case below.

2023-01-13 13:30 UTC, f-brinkmann approved these changes

2023-01-31 07:55 UTC, sikersten requested changes
Thanks for implementing!
I tested with a Signal object, `s = pf.Signal([2, -1, 0, np.nan], 44100)`. The mode `nan_policy='omit' ` does not seem to work in this case. Could you please add a test and check what the reason is?

2023-02-02 18:14 UTC, twennemann commented
> Thanks for implementing! I tested with a Signal object, `s = pf.Signal([2, -1, 0, np.nan], 44100)`. The mode `nan_policy='omit' ` does not seem to work in this case. Could you please add a test and check what the reason is?

To apply normalization we calculate the normalized signal as followed:
`normalized_signal = signal.copy() * target / reference_norm`

If the signal object, which is used for a calculation, is type `pf.Signal` and it includes NaN values, every value will be returned with NaN.  So this problem needs to be fixed in the Signal class.

2023-03-03 12:17 UTC, sikersten approved these changes

2023-03-03 12:17 UTC, merged