Fix bugs and failing test caused by numpy update
pyfar/pyfar pull request #409
Opened 2022-12-21 08:42 UTC by f-brinkmann

### Which issue(s) are closed by this pull request?

- `dsp.find_impulse_response_start` still used `numpy.int`, which has been removed from numpy
- the test for `dsp.normalize` failed because the test tolerance was to low

### Changes proposed in this pull request:

- used `int` instead of `numpy.int` in `dsp.find_impulse_response_start`
- add test tolerance in `tests/test_dsp_normalize.py`

2022-12-21 08:45 UTC, ahms5 approved these changes

2023-01-06 13:11 UTC, mberz requested changes
Using numpy testing functionality should make this much clearer and more explicit.

2023-01-06 13:11 UTC, mberz commented on tests/test_dsp_normalize.py
> +    assert np.abs(1 - np.max(np.abs(time.time))) < 1e-15
```suggestion
    npt.assert_allclose(np.max(np.abs(time.time)), 1)
```

2023-01-06 13:11 UTC, mberz commented on tests/test_dsp_normalize.py
> +    assert np.abs(1 - np.max(np.abs(freq.freq))) < 1e-15
```suggestion
    npt.assert_allclose(np.max(np.abs(freq.freq)), 1)
```

2023-01-12 12:44 UTC, mberz approved these changes

2023-01-12 15:01 UTC, sikersten approved these changes

2023-01-20 11:27 UTC, merged