Enforce numeric data in signals
pyfar/pyfar pull request #435
Opened 2023-02-10 13:34 UTC by f-brinkmann

### Which issue(s) are closed by this pull request?

Closes #431 

### Changes proposed in this pull request:

- Check for non-numerical data in `Signal.__init__`

I did not find a way to check for boolean data, because it is converted to float when calling `np.atleast_2d(data)`. Any ideas?

2023-02-24 08:00 UTC, ahms5 submitted a review, later dismissed

2023-03-01 12:16 UTC, sikersten submitted a review, later dismissed

2023-03-16 19:01 UTC, mberz requested changes
This actually needs to checked in the setter methods of Signal as well.

2023-03-17 06:54 UTC, f-brinkmann commented
Good point, I added it to the freq and freq_raw setter so far. I think the time setter is refactored in #396. Should we rather add this as todo there to avoid conflicts? The check is now a static class method so it would be easy to include.

2023-03-24 12:20 UTC, f-brinkmann commented
We decided to postpone this until #396 is merged

2023-10-12 21:09 UTC, f-brinkmann commented
Closed in favor of #505 which was done for the new Audio classes that can handle complex time data.

2023-10-12 21:09 UTC, closed without merging