Add concatenate function
pyfar/pyfar pull request #452
Opened 2023-03-29 17:42 UTC by twennemann

### Which issue(s) are closed by this pull request?

Closes #

### Changes proposed in this pull request:

- Add a concatenation function, concatenating Signals along specified channels.
- Add broadcasting parameter, which broadcasts the signals into largest cdim and a common shape, ignoring caxis.

2023-04-05 11:58 UTC, twennemann commented
I tried to adjust the comment of the merged signal so that the comments can be assigned to the data in the merged signal. First, to the comment of the merged signal is passed on which caxis the signals were merged. If there is a comment in one of the input Signals, that comment is appended, as well as the corresponding channels on caxis.
Questions:
- Is it right to call it channels?
- Do we start counting at 0 or at 1? For example `first_signal.cshape[caxis]` is 3, would we say the comment corresponds to channel 1-3 or 0-2?

2023-04-28 11:36 UTC, f-brinkmann requested changes

2023-04-28 11:36 UTC, f-brinkmann commented on pyfar/utils.py
> +        their corresponding signal position in the input tuple.
I would suggest to simply the comments handling. Use an empty string if the provided comment. Discard comments from input data. What do the others think?

2023-04-28 11:36 UTC, f-brinkmann commented on pyfar/utils.py
> +        for i, s in enumerate(signals):
using
```suggestion
        for signal, cshape in zip(signals, cshapes):
```
might be better to read and avoid indexing

2023-04-28 11:36 UTC, f-brinkmann commented on pyfar/utils.py
> +        sig_channel += s.cshape[caxis]
See above. Should we simplify this?

2023-05-03 06:16 UTC, f-brinkmann approved these changes
Thanks for implementing. Approved and awaiting a discussion on the comment handling...

2023-05-03 06:16 UTC, f-brinkmann commented on pyfar/utils.py
> +        except in the dimension corresponding to axis (the first, by default).
Better to use `caxis` instead of axis.

2023-05-11 15:58 UTC, f-brinkmann requested changes
I just recognized that this would need small changes to work for complex signals. But I would suggest to make this a separate pull.
- the complex variable must be obtained from `_assert_matching_meta_data` which requires #464  
- before concatenating `s._data` the domain must be set to `time` if the input data contains a complex `Signal` object.
- the `complex` flag must be set when returning `Signal` or `TimeData` objects

2023-05-11 15:58 UTC, f-brinkmann commented on pyfar/utils.py
> +    [signals[0]._assert_matching_meta_data(s) for s in signals]
Just a tiny note - I think you can pass all audio objects at the same time
```suggestion
    _assert_matching_meta_data(signals)
```

2023-05-11 15:58 UTC, f-brinkmann commented on pyfar/utils.py
> +    [signals[0]._assert_matching_meta_data(s) for s in signals]
Just a tiny note - I think you can pass all audio objects at the same time
```suggestion
    _assert_matching_meta_data(signals)
```

2023-06-02 11:15 UTC, f-brinkmann approved these changes

2023-06-26 08:19 UTC, ahms5 requested changes
Thank you for implementing, i just have a few comments on the usage und docstring

2023-06-30 11:25 UTC, f-brinkmann commented on pyfar/utils.py
> +    signals : tuple of Signal, TimeData or FrequencyData
good to have, but should be another function

2023-07-12 14:52 UTC, f-brinkmann approved these changes

2023-07-14 11:23 UTC, merged