adapt convolution for complex singals and implement testing
pyfar/pyfar pull request #461
Opened 2023-04-28 12:27 UTC by tluebeck

adapt convolution and implement tests

2023-05-03 06:46 UTC, f-brinkmann requested changes
Thanks for the implementation. I have two general comments
- Can you add a one line docstrings to the tests, e.g., '''Test dsp.convolve with complex signals'''?
- Should we use signals for testing that actually have an imaginary part?

2023-05-03 06:46 UTC, f-brinkmann commented on pyfar/dsp/dsp.py
> +        is_result_complex = False
Could be shortened
```suggestion
     complex = True if res.dtype.kind == 'c' else False
```

2023-05-11 15:59 UTC, f-brinkmann approved these changes

2023-06-26 08:32 UTC, ahms5 reviewed
Thanks for implementing, looks fine to me, but I just have on question.

2023-12-11 12:06 UTC, ahms5 reviewed
Thanks for the effort. just one comment.

2023-12-11 12:06 UTC, ahms5 commented on tests/test_dsp.py
> +def test_convolve_mode_and_method_complex(method, mode, desired):
How about testing complex signals and also one complex and one real signal.

2023-12-17 12:50 UTC, pingelit approved these changes
Thanks for implementing!

2023-12-18 09:57 UTC, ahms5 approved these changes

2023-12-19 00:58 UTC, merged