[fractional_time_shift] add missing arg to docstr
pyfar/pyfar pull request #484
Opened 2023-08-10 16:54 UTC by artpelling

Adds a missing parameter to the docstring. My suggestion would be to also accept `'seconds'` as a unit.

2023-08-11 11:29 UTC, ahms5 reviewed
Thank you for implementing, good idea to add 'seconds'. maybe we need to also add a test for seconds.

2023-09-05 08:36 UTC, f-brinkmann requested changes
For discussion: we use `'s'` for seconds in various places If we change this, I think we sould be consistent everywhere.

2023-09-05 08:42 UTC, artpelling commented
> For discussion: we use `'s'` for seconds in various places If we change this, I think we sould be consistent everywhere.

yeah I realized the same thing. I like 'seconds' as it is more clear but maybe not in this PR :)

2023-09-05 08:53 UTC, f-brinkmann approved these changes
Agreed, can you open an issue for that?

2023-09-06 12:53 UTC, ahms5 commented
tests are fixed now in develop, you can merge dev into your branch

2023-09-29 11:32 UTC, merged