replace old naming convention description
pyfar/pyfar pull request #544
Opened 2024-02-21 10:32 UTC by ahms5

### Changes proposed in this pull request:

- fix concepts explaination

2024-02-22 09:41 UTC, f-brinkmann approved these changes
Thanks for catching :)

2024-02-23 07:21 UTC, sikersten commented on pyfar/_concepts/coordinates.py
> +in spherical coordinates. The available coordinate systems are shown
```suggestion
Coordinate systems are defined by their domain (cartesian, spherical,
cylindrical), and, if multiple definitions of the domain exist, also by
their convention. The available coordinate systems are shown
```

2024-02-23 11:08 UTC, pingelit requested changes

2024-02-23 11:08 UTC, pingelit commented on pyfar/_concepts/coordinates.py
> +in spherical coordinates. The available coordinate systems are shown
I second that.

2024-03-08 07:33 UTC, f-brinkmann approved these changes

2024-03-12 09:56 UTC, sikersten approved these changes

2024-03-12 16:08 UTC, mberz approved these changes

2024-03-12 16:10 UTC, merged