Remove-examples
pyfar/pyfar pull request #565
Opened 2024-03-28 09:07 UTC by ahms5

### Changes proposed in this pull request:

- remove examples
- change despription in readme accoringly, ref to the gallery

open question: merge to main or develop?

2024-03-30 07:24 UTC, f-brinkmann commented
Should we wait for https://github.com/pyfar/gallery/pull/51 with this? In this case, we could directly get rid of contributing as well and update the readme only once?

2024-04-05 10:15 UTC, pingelit requested changes
Thanks for updating this.

One minor language change. Then I approve.

2024-04-05 10:15 UTC, pingelit commented on README.rst
> +Check out the `pyfar.org`_ for a tour trought the pyfar
```suggestion
Check out `pyfar.org`_ for a tour through the pyfar
```

2024-04-05 12:03 UTC, mberz commented
I'd suggest merging to main.

2024-04-10 13:54 UTC, ahms5 commented
replaced by #574 to merge to main

2024-04-10 13:54 UTC, closed without merging