Fixes #587: Improved FFT Normalization Handling in Arithmetic Operations
pyfar/pyfar pull request #593
Opened 2024-04-21 14:53 UTC by robogeisha

### Which issue(s) are closed by this pull request?

Closes #587

### Summary 
Improvement on the **_match_fft_norm** function to support a wider range of arithmetic operations and introduction of a **norm_override** capability. Changes aim to improve the function's flexibility and its ability to handle exceptions more gracefully.

### Changes proposed in this pull request:

**_Main Changes_**

- Added support for 'multiply', 'divide', 'add', and 'subtract' operations. Previously, the function was limited to handling division implicitly through a boolean flag.
- norm_override: Introduced an optional parameter to explicitly set the result normalization, allowing for more control over the function's output regardless of the input norms.
- Implemented warnings for invalid norms and unsupported operations, which helps in identifying configuration errors without halting the execution.

**_Changes to Tests_**

- Adjusted some of the existing unit tests to accommodate the introduction of the operation parameter, reflecting the new method signature and expanded functionality.
- Introduced new tests to validate the norm override feature and the correct handling of various operations.
- Added tests to verify that warnings are correctly issued for invalid norm inputs and unsupported operations.

### Areas for Review

- The implementation of the new operation parameter and how it integrates with existing logic.
- The handling of the norm_override parameter and its precedence in normalization determination.
- Error and warning mechanisms.

2024-04-21 15:22 UTC, f-brinkmann commented
Hi, and thanks for the Contribution!  It's a hard to see, what you changed because there are many, many files touched. Can you please revoke the changes in `tests/test_plot_data` (we only update those, when we change something in the plot module), add `pyfar_venv` to `.gitignore`, and revoke all changes that only change the code style (e.g., changing everystring to use `"` instead of `'`). I assume the latter might have happened automatically.

2024-04-21 20:59 UTC, robogeisha commented
thank you for the feedback and sorry for the confusion. I  downloaded the library through pip in my virtual environment then moved the files to my fork, which was obviously a bad decision. Update coming soon.

2024-04-24 06:34 UTC, f-brinkmann requested changes
Thanks for the effort, I could now see what you changed. We did not discuss this issue in the dev team yet, but I think we are looking for a different kind of solution. You relaxed the rules that we apply for arithmetics to raise a warning instead of an error of the case from #587 occurs. I assume, we rather want to adapt the checks to not neither raise an error nor a warning but still raise errors if the other rules are violated.

I'm not at Audiotechnik today, but I will be in office tomorrow and on Friday. If you want you can drop by to discuss the solution. You can call before to make sure I'm not in a meeting :)

2024-04-24 06:34 UTC, f-brinkmann commented on pyfar/classes/audio.py
> -        Otherwise empty tuple.
I prefer the explicit documentation with a description of each return parameter.

2024-04-24 06:34 UTC, f-brinkmann commented on pyfar/classes/audio.py
> +    operation_type = "divide" if division else "multiply"
This is a bit misleading. The reason we check for the division is that [different rules apply in this case](https://pyfar-gallery.readthedocs.io/en/latest/gallery/interactive/pyfar_arithmetics.html#DFT-normalization-and-arithmetic-operations). But the operation can be addition, subtraction or multiplication. Maybe using the `division` flag as before is cleaner.

2024-04-24 06:34 UTC, f-brinkmann commented on pyfar/classes/audio.py
> -    Other combinations raise an error.
This actually gives more information than the new version, which might be helpfull for debugging. We should keep the old version IMO

2024-04-24 06:34 UTC, f-brinkmann commented on pyfar/classes/audio.py
> +        The FFT normalization of the first signal. Must be one of 'none',
We have a convention to show input values as code in the docstrings. Thats why we for example used \`\`'none'\`\`. This should be reverted.

2024-04-24 06:34 UTC, f-brinkmann commented on pyfar/classes/audio.py
> +        'multiply', 'divide', 'add', or 'subtract'.
See comment above, I would be in favor of keeping the `division` flag and its old description.

2024-04-24 06:34 UTC, f-brinkmann commented on pyfar/classes/audio.py
> +        about operations involving 'none' normalization.
We actually want to be strict here and raise errors, not warning in case something is not as defined in our rules for arithmetics.

2024-06-14 12:22 UTC, f-brinkmann commented
This was fixed in #606

2024-06-14 12:22 UTC, closed without merging