Relax arithmetic rules in case only one audio object is involved
pyfar/pyfar pull request #606
Opened 2024-05-12 12:28 UTC by f-brinkmann

### Which issue(s) are closed by this pull request?

Closes #587 

### Changes proposed in this pull request:

- Bypass rules for fft norm if only one audio object is involved in the opeeration

### For discussion

I discovered that we had a test that explicitly does not allow `1/signal` if the FFT norm is not `'none'`. I did not remove this test yet. Do we want to stay hard?

2024-05-13 06:59 UTC, ahms5 requested changes
Thank you for fixing! How about testing if its really working, to make sure it will work in future as well.

2024-05-13 07:02 UTC, f-brinkmann commented
> Thank you for fixing! How about testing if its really working, to make sure it will work in future as well.

I did a quick check locally, and everything works. I'll add it if we decide to change the behaviour - I added a todo in the PR description to make sure we dont forget. Just didn't want to do too much work that might be discarded :)

2024-05-13 07:51 UTC, ahms5 requested changes
I would suggest not to change the behaviour of ``_match_fft_norm`` instead jsut call it if we have more then 1 Audio object

2024-05-13 07:51 UTC, ahms5 commented on pyfar/classes/audio.py
> +    for d in enumerate(data):
```suggestion
    for _, d in enumerate(data):
```
otherwise sth breaks

2024-05-13 07:51 UTC, ahms5 commented on pyfar/classes/audio.py
> +                        fft_norm, d.fft_norm, division, n_audio_objects)
```suggestion
                    fft_norm = d.fft_norm if n_audio_objects < 2 else \
                        _match_fft_norm(fft_norm, d.fft_norm, division)
```
I would not change the behaviour of _match_fft_norm, instead i would just call it, if we have more then 1 audio object.

2024-05-13 07:51 UTC, ahms5 commented on pyfar/classes/audio.py
> +def _match_fft_norm(fft_norm_1, fft_norm_2, division=False, n_audio_objects=2):
```suggestion
def _match_fft_norm(fft_norm_1, fft_norm_2, division=False):
```
then there would be no need to change the behaviour here.

2024-05-16 11:44 UTC, f-brinkmann commented
@ahms5 implemented your changes as suggested. Now I'm waiting for the weekly before changing any tests

2024-05-27 11:37 UTC, ahms5 approved these changes

2024-06-07 12:10 UTC, merged