add docstring rules for ruff
pyfar/pyfar pull request #614
Opened 2024-05-27 10:15 UTC by ahms5

- add D100 - D107 to ruff and add remaining docs
-
-

2024-06-05 11:19 UTC, f-brinkmann requested changes
Thanks for the effort. I generarly like having this. In some cases you added documentation that shows up in the build docs:

- classes/orientations.py
- dsp/dsp.py
- utils.py

In those cases we should put in a little more effort. But maybe wait until we have the opinon from others. In case of utils.py a proper docstring is introduced in #591

2024-07-08 12:05 UTC, ahms5 reviewed
marked all parts of the document that are part of the document.

2024-07-08 12:05 UTC, ahms5 commented on pyfar/classes/orientations.py
> +"""This module contains the Orientations class. """
shows up in doc

2024-07-08 12:05 UTC, ahms5 commented on pyfar/dsp/__init__.py
> +"""Digital signal processing functions."""
shows up in doc

2024-07-08 12:05 UTC, ahms5 commented on pyfar/io/__init__.py
> +"""
shows up in doc

2024-07-08 12:06 UTC, ahms5 commented on pyfar/classes/orientations.py
> +"""This module contains the Orientations class. """
maybe we should shift the doc from the class to the toplevel

2024-08-26 15:59 UTC, f-brinkmann approved these changes

2024-09-07 15:22 UTC, merged