Harmonize class documentation
pyfar/pyfar pull request #631
Opened 2024-06-17 13:06 UTC by f-brinkmann

Some classes still used an explicit documentation of their magic methods, which I think is not good practive.

### Changes proposed in this pull request:

- Move documentation of `Orientation.__init__` to the class docstring and make interactive links
- Move documentation from Audio objects (Signal/TimeData/FrequencyData) `__init__` to the class docstring.
- Move Information from Audio objects `__getitem__`, `__setitem__`, and `__iter__` to the module dosctring.

In the latter case, we might consider adding an example notebook to the gallery instead. The information in the docs on this is rather sparse. But I did not want to add stuff in this pull.

2024-06-19 08:14 UTC, ahms5 reviewed
Do you have any reference why it is bad? I just found [references](https://docs.astral.sh/ruff/rules/undocumented-magic-method/) why you should do it, but they also dont really tell why. And i found [sth ](https://github.com/PyCQA/pydocstyle/issues/60#issuecomment-31206791) that says one should add docstrings for init functions.
(maybe you have discussed it at the weeky and i was not participating)

2024-06-21 06:11 UTC, f-brinkmann commented
Maybe the formulation was a little unlucky. I am very much in favour of documenting the behaviour of the magic methods but without showing, e.g., `__rmul__` and `__init__` explicitly in the docs and you don't use the magigc methods with `Signal.__init__()`. Moreover, those names are likely riddles to many new users. I think with the newer classes, we always document the init behaviour as part of the docstring and other methods like arithmetic operations in the module docstring or examples in the gallery.

This is not speaking against adding docstrings to magic methods, which I think is good practice to aid development.

2024-06-25 09:42 UTC, sikersten approved these changes

2024-06-26 06:24 UTC, ahms5 requested changes
Thank you, maybe one point to discuss next time

2024-06-26 19:36 UTC, f-brinkmann commented
Maybe this is a good point for general discussion. If we keep it here, there are magic functions in other classes we should add to the docs for consistenty...

2024-07-05 12:07 UTC, ahms5 approved these changes

2024-07-05 12:08 UTC, merged