add channel concatenation function
pyfar/pyfar pull request #65
Opened 2020-12-19 08:40 UTC by mberz

### Which issue(s) are closed by this pull request?

Closes #None

### Changes proposed in this pull request:

- Add a concatenation function, concatenating Signals along specified channels.

2020-12-19 13:09 UTC, f-brinkmann commented on pyfar/signal.py
> +    else:
this case might not be catched:
`elif second.comment is not None: comment = str(second.comment)`

2020-12-19 13:11 UTC, f-brinkmann requested changes
see comment on `elif` case

2021-01-08 10:56 UTC, mberz commented
May be meaningful to implement this as a class method rather than a function to avoid confusion with merges of other classes.

2023-01-20 10:44 UTC, twennemann commented
We had the idea, to add an `ignore_axis` parameter in `utils.broadcast_scape`, so certain caxis will retain for concatenation.
Example:
We want to concatenate `signal1.cshape = (1, 2, 3)`  and `signal2.cshape = (1, 1, 2)`.                                                                                   
So `utils.broadcast_cshape(signal2, ignore_axis=-1)` will return `signal2.cshape = (1, 2, 2)`.
The concatenated signal will subsequently returned with `signal_conc.cshape = (1, 2, 5)`.

2023-04-14 11:06 UTC, mberz commented
Closing, replaced by more recent PR #452.

2023-04-14 11:06 UTC, closed without merging