Add complex 2d plots
pyfar/pyfar pull request #656
Opened 2024-07-21 13:11 UTC by tluebeck

### Which issue(s) are closed by this pull request?

Closes #

### Changes proposed in this pull request:

-
-
-

2024-07-22 12:10 UTC, ahms5 requested changes
Thanks, it think after adding baseline it should be fine.

2024-07-22 12:10 UTC, ahms5 commented on tests/test_plot.py
> +    filename = function.__name__
```suggestion
    filename = f'complex_2d_{function.__name__}'
```
I think otherwise it will cmp vs the wrong files.

2024-08-15 13:23 UTC, f-brinkmann commented on pyfar/plot/line.py
> +        ``left`` or ``right`` to specify which side of a spectrum is plotted.
I would suggest to give a little more information and also mention the default here and everywhere else:

```suggestion
    side : str, optional
        ``'right'`` to plot the right-sided spectrum containing the positive
        frequencies, or ``'left'``to plot the left-sided spectrum containing
        the negative frequencies (only possible for complex Signals). The
        default is ``'right'``.
```

2024-08-15 13:25 UTC, f-brinkmann commented on pyfar/plot/line.py
> +        plotted. The default is ``real``.
I would mention that imag and abs can not be used for non-complex Signals here and everywhere else:

```suggestion
    mode : str
        ``'real'``, ``'imag'``, or ``'abs'`` to specify if the real part, imaginary
        part or absolute value of the time data is plotted. ``'imag'`` and ``'abs'```
        can only be used for complex Signals. The default is ``'real'``.
```

2024-08-15 13:26 UTC, f-brinkmann requested changes
+1 for changing the file names of the baseline plots as suggested by ahms. Apart from that I only suggest to be more verbose in the docs - thanks a lot!

2024-08-19 10:04 UTC, ahms5 approved these changes
looks good to me, thank you, we just need to set ``create_baseline`` to ``False`` again.

2024-08-20 13:35 UTC, ahms5 approved these changes

2024-08-20 13:52 UTC, f-brinkmann approved these changes

2024-08-20 13:53 UTC, merged