deprecate Python 3.8
pyfar/pyfar pull request #683
Opened 2024-09-06 13:13 UTC by f-brinkmann

### Changes proposed in this pull request:

End support for Python 3.8 as discussed during the weekly and required by #682

2024-09-06 15:11 UTC, ahms5 submitted a review, later dismissed

2024-09-09 08:02 UTC, hoyer-a requested changes
Thanks!

In the readme's installation section is a note "Requires Python 3.8. or higher", we should update that too.

2024-09-09 08:09 UTC, f-brinkmann commented
Thanks for noting. I fixed it.

2024-09-09 08:27 UTC, hoyer-a approved these changes

2024-09-10 11:49 UTC, sikersten approved these changes

2024-09-10 12:02 UTC, ahms5 approved these changes

2024-09-10 12:02 UTC, merged