ruff: automatic docstring rules after numpy convention
pyfar/pyfar pull request #685
Opened 2024-09-08 09:54 UTC by ahms5

since we are up to use numpy conventions (see contribution guidelines) I suggest to apply this set here.
I ignored a couple of rules, since we never really followed them:
```
    "D200", # One-line docstring should fit on one line with quotes
    "D202", # No blank lines allowed after function docstring
    "D205", # 1 blank line required between summary line and description
    "D401", # First line should be in imperative mood
    "D404", # First word of the docstring should not be "This"
```

https://docs.astral.sh/ruff/faq/#does-ruff-support-numpy-or-google-style-docstrings

2024-09-10 12:08 UTC, sikersten commented
Where do these `r"""` additions come from and why are they necessary?

2024-09-12 21:08 UTC, mberz requested changes
The changes using raw docstrings break latex formulas, which were properly escaped before these changes. 
Please either revert the change to raw docstrings or remove the escape sequence of backslashes.

2024-09-13 13:18 UTC, ahms5 commented
fixed all maths in doc, ready to review

2024-10-23 14:01 UTC, f-brinkmann approved these changes

2024-10-25 10:44 UTC, hoyer-a requested changes

2024-10-25 10:44 UTC, hoyer-a commented on pyfar/classes/coordinates.py
>          \\vec{a} \\cdot \\vec{b}
The formula isn't displayed correctly in the docs, probably because of the double backslashes.

2024-10-25 10:44 UTC, hoyer-a commented on pyfar/classes/coordinates.py
>          \\vec{a} \\times \\vec{b}
same here

2024-10-25 10:49 UTC, hoyer-a requested changes

2024-10-25 10:49 UTC, hoyer-a commented on pyfar/classes/transmission_matrix.py
>      def input_impedance(self, Zl: complex | FrequencyData) -> FrequencyData:
Also here

2024-10-25 10:49 UTC, hoyer-a commented on pyfar/classes/transmission_matrix.py
> +        r"""Calculates the output impedance given the load impedance Zl at the
And here

2024-10-25 11:52 UTC, mberz reviewed
It's probably a good idea to check for unnecessarily escaped backslashes via search & replace or similar. The change to raw docstrings makes them obsolete in multiple places and results in equation rendering issues.

2024-11-08 10:13 UTC, mberz approved these changes

2024-11-08 10:13 UTC, merged