Ruff: A, Avoid builtin function and type shadowing.
pyfar/pyfar pull request #690
Opened 2024-09-08 11:42 UTC by ahms5

### Which issue(s) are closed by this pull request?

See #647

### Changes proposed in this pull request:

- apply for internal use
- how ro proceed with audio_subtypes and default_audio_subtype?

2024-09-16 08:29 UTC, f-brinkmann requested changes
Thanks for the effort. I think we should add two little tests for the deprectations

2024-09-16 08:29 UTC, f-brinkmann commented on pyfar/io/io.py
> +def audio_subtypes(audio_format=None):
I'm on favour of changing this, but we should also a test if this raises an error for pyfar>=0.9.0. There should be examples in test_deprecations for other cases.

2024-09-16 08:29 UTC, f-brinkmann commented on pyfar/io/io.py
> +def default_audio_subtype(audio_format):
See above

2024-09-16 09:00 UTC, ahms5 commented
this should release in v0.7.0 due to the deprecation stuff

2024-09-16 09:49 UTC, f-brinkmann requested changes
I think I spotted a typo...

2024-09-16 09:49 UTC, f-brinkmann commented on tests/test_deprecations.py
> +                                     sampling_rate=44100)
```suggestion
            pf.io.default_audio_subtype(format='wav')
```

2024-09-16 14:30 UTC, f-brinkmann approved these changes
Damn you autocomplete ;)

2024-09-17 10:03 UTC, sikersten submitted a review, later dismissed

2024-09-18 14:29 UTC, hoyer-a submitted a review, later dismissed

2024-09-20 12:18 UTC, merged