deprecate 'frequencies' reconstructing_fractional_octave_bands()
pyfar/pyfar pull request #725
Opened 2024-11-19 09:59 UTC by hoyer-a

deprecate `frequencies` return in `reconstructing_fractional_octave_bands()`

Closes #657

2024-11-21 12:20 UTC, sikersten approved these changes
Thanks for taking care!
Is there something we can do about the issue with the input parameters mentioned in #657?

2024-11-21 12:55 UTC, hoyer-a commented
Ah, yes. All the other filters have `sampling_rate` as the last parameter. I can move the parameter in `fractional_octave_bands` to the end to match the rest of `dsp.filter`. Concerning the default for num_fractions, i think setting `num_fractions=1` in `fractional_octave_bands` would be ok too.

Any opinions and can i do it here or is it a beer?

2024-11-22 09:16 UTC, f-brinkmann submitted a review, later dismissed

2024-11-22 11:25 UTC, ahms5 requested changes
thank you for taking care! just a minor thing.

2024-11-22 11:25 UTC, ahms5 commented on pyfar/dsp/filter/fractional_octaves.py
> +        deprecated in pyfar 0.9.0.
maybe we can add what to use instead.

2024-11-22 11:25 UTC, ahms5 commented on pyfar/dsp/filter/fractional_octaves.py
> +                   " 0.9.0"), PyfarDeprecationWarning, stacklevel=2)
see above

2024-11-25 09:19 UTC, ahms5 commented on pyfar/dsp/filter/fractional_octaves.py
> +        deprecated in pyfar 0.9.0.
yes

2024-11-29 13:01 UTC, mberz requested changes
I would also adapt the example to use the respective function for getting the center frequencies.

2024-12-06 09:59 UTC, mberz reviewed
Just to make it a bit cleaner. Otherwise looking good.

2024-12-06 09:59 UTC, mberz commented on pyfar/dsp/filter/fractional_octaves.py
> +        >>> y, _ = pf.dsp.filter.reconstructing_fractional_octave_bands(x)
```suggestion
        >>> y = pf.dsp.filter.reconstructing_fractional_octave_bands(x)[0]
```

2024-12-06 09:59 UTC, mberz commented on pyfar/dsp/filter/fractional_octaves.py
> +        ...    frequency_range=(60, 16000))
```suggestion
        >>> f = pf.dsp.filter.fractional_octave_frequencies(
        ...    frequency_range=(60, 16000))[1]
```

2024-12-06 18:55 UTC, mberz approved these changes
All good, thanks!

2024-12-18 13:50 UTC, f-brinkmann approved these changes

2024-12-18 14:58 UTC, ahms5 approved these changes

2024-12-19 12:30 UTC, sikersten approved these changes

2024-12-20 13:32 UTC, merged