speed of sound calculation
pyfar/pyfar pull request #732
Opened 2024-12-13 13:44 UTC by ahms5

2024-12-19 12:24 UTC, sikersten commented
General question:
The function name "..._simple" suggests that their are other ways of calculating it. Would it make sense to combine the different methods into a class SpeedOfSound, which, e.g., has a method .from_temperature()?

2024-12-19 12:26 UTC, sikersten commented
I just saw that @mberz already suggested something with a dataclass in #428

2025-01-11 21:47 UTC, ahms5 commented on pyfar/constants/speed_of_sound.py
> +    based on the temperature.
```suggestion
    of the ideal gas law based on the temperature.
```

2025-02-07 11:59 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +        c = 343.2 \cdot \sqrt{\frac{t + 273.15}{293.15}} m/s
```suggestion
        c = 343.2 \cdot \sqrt{\frac{T + 273.15}{293.15}} m/s
        
        where, T denotes the temperatur in °C.
```

2025-02-07 11:59 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +    ISO 17497-1 [#]_.
Why is the second reference necessary?
```suggestion
    Calculation is in accordance with ISO 9613-1 [#]_.
```

2025-02-07 11:59 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +           coefficient in a reverberation room.
Is this reference needed?
```suggestion
```

2025-02-11 07:43 UTC, ahms5 commented on pyfar/constants/speed_of_sound.py
> +           coefficient in a reverberation room.
the fomula is not mentioned in 9613-1, its just mentioned in ISO 17497-1:2004 and refering to 9613-1. threfore I have added both.

2025-02-11 10:35 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +    where, T denotes the temperature in °C.
```suggestion
    Calculation is in accordance with ISO 9613-1 [#]_ and  ISO 17497-1 [#]_,
    with the reference air temperature of 20°C (293.15 K).

    .. math::

        c = 343.2 \cdot \sqrt{\frac{T + 273.15}{293.15}} m/s

    where, T denotes the temperature in °C.
```

2025-02-11 10:35 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +           coefficient in a reverberation room.
Thanks for the info! As both the T0=293.15 K and c = 343,2 (T/T0)^1/2 are also mentioned in 9613, I think it makes sense reformulate as suggested above.

2025-02-11 13:40 UTC, ahms5 commented on pyfar/constants/speed_of_sound.py
> +    where, T denotes the temperature in °C.
fixed it, i did nto found the equation in 9613 before, but everthing is there.

2025-02-12 16:20 UTC, f-brinkmann submitted a review, later dismissed

2025-02-14 13:50 UTC, sikersten requested changes

2025-02-14 13:50 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +        c = 343.2 \cdot \sqrt{\frac{t + 293.15}{t_0 + 293.15}} \mathrm{m/s}
```suggestion
        c = 343.2 \cdot \sqrt{\frac{t + 273.15}{t_0 + 273.15}} \mathrm{m/s}
```

2025-02-14 15:00 UTC, f-brinkmann approved these changes

2025-02-21 10:17 UTC, sikersten approved these changes

2025-02-21 13:50 UTC, merged