add air attenuation after iso
pyfar/pyfar pull request #734
Opened 2024-12-14 12:24 UTC by ahms5

2024-12-16 12:53 UTC, ahms5 commented on pyfar/constants/air_attenuation.py
> +def _p_sat_water(temperature):
this is was replaced by saturation_vapor_pressure and is not used anymore, its just temporary here and is comping from #503

2024-12-18 08:40 UTC, f-brinkmann requested changes
Thanks for implementing. Looks mostly fine to me. I checked against our Matlab implementation. Results generally agree but are slightly different. I think this is related to the improved Magnus Formula, which we didn't implement. One general question:

Do we want to add a flag to return the air attenuation in dB or as energetic property? The latter is used in common approximations of the reverberation time, and might be useful as well. I would be in favor of this.

2024-12-18 08:40 UTC, f-brinkmann commented on pyfar/constants/air_attenuation.py
> +def air_attenuation_iso(
Is there another air attenuation that we want to implement? Not sure if we need the ISO in the name. In other places, we also don't mention the source in the function name.

2024-12-18 08:40 UTC, f-brinkmann commented on pyfar/constants/air_attenuation.py
> +            np.array(atmospheric_pressure, dtype=float), shape)
Is the explicit broadcasting needed? I would suggest to convert input to numpy arrays in any case and maybe only
```
try:
    _ = np.broadcast_shapes(...)
except: ValueError as e:
    raise ValueError('some message') from e
```

2024-12-18 08:40 UTC, f-brinkmann commented on pyfar/constants/air_attenuation.py
> +    accuracy : float, array_like, optional
I would suggest to return both as FrequencyData objects

2024-12-18 08:40 UTC, f-brinkmann commented on pyfar/constants/air_attenuation.py
> +    accuracy : float, array_like, optional
I think the accuracy is not tested.

2024-12-18 08:40 UTC, f-brinkmann commented on pyproject.toml
> +    "matplotlib<3.10",
We could discuss, which solution we want to use...

2025-01-08 08:36 UTC, ahms5 commented on pyproject.toml
> +    "matplotlib<3.10",
```suggestion
    "matplotlib",
```

2025-01-08 08:48 UTC, ahms5 commented
In the standard, there is a table of results that I use for comparison during the tests. The Magnus formula in the ITA-Toolbox and AKtools was not well documented, as it referenced the manual of a humidity measuring device. Therefore, I searched for a more reliable reference.

2025-01-21 12:12 UTC, ahms5 commented on pyfar/constants/air_attenuation.py
> +            np.array(atmospheric_pressure, dtype=float), shape)
yes for the accuracy later on

2025-01-23 13:31 UTC, f-brinkmann requested changes
Thanks for the effort the computation and testing looks good to me - I checked it against our Matlab implementation from AKtools. But there might be an error when computing the accuracy. For `alpha, m, aaccuracy = pf.constants.air_attenuation(20, 1e3, .5, 101325)` I get `-1` for the accuracy, where it shoud be `10` I think.

2025-01-23 13:37 UTC, ahms5 commented on pyfar/constants/air_attenuation.py
> +        atmospheric absorption. The cshape of the output is the broadcast
its a FrequencyData object, do we need to explain that anywhere. I could add it into the function describtion, what do you think?

2025-02-07 12:35 UTC, sikersten commented on pyfar/constants/air_attenuation.py
> +        Relative humidity in the range of 0 to 1.
```suggestion
        Relative humidity in the range from 0 to 1.
```

2025-02-07 12:35 UTC, sikersten commented on pyfar/constants/air_attenuation.py
> +    freq2pressure = frequencies/atmospheric_pressure
```suggestion
    freq_pressure_ratio = frequencies/atmospheric_pressure
```

2025-02-07 12:35 UTC, sikersten commented on pyfar/constants/air_attenuation.py
> +    accuracy = np.zeros(shape) - 1
I wonder if there a good alternatives to -1, e.g., nan, None, 0?

2025-02-07 12:35 UTC, sikersten commented on pyfar/constants/air_attenuation.py
> +            - air temperature: greater than 200 K (- 73 °C)
I think the standard states -20 to 50 for the 20% accuracy

2025-02-07 12:35 UTC, sikersten commented on pyfar/constants/air_attenuation.py
> +    temp_2_mask = (-70 <= temperature) & (temp_1_mask is False)
Sure about this temperature range for 20% accuracy?

2025-02-07 12:35 UTC, sikersten commented on pyfar/constants/air_attenuation.py
> +    temp_2_mask = (-70 <= temperature) & (temp_1_mask is False)
I think this needs to be -73 instead of -70

2025-02-07 12:35 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +def test_air_attenuation_iso(
```suggestion
def test_air_attenuation(
```

2025-02-07 12:35 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +def test_air_attenuation_iso_array(
```suggestion
def test_air_attenuation_array(
```

2025-02-07 12:35 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +def test_air_attenuation_iso_inputs():
```suggestion
def test_air_attenuation_inputs():
```

2025-02-07 12:35 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +def test_air_attenuation_iso_broadcastable():
```suggestion
def test_air_attenuation_broadcastable():
```

2025-02-07 12:35 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +def test_air_attenuation_iso_limits():
```suggestion
def test_air_attenuation_limits():
```

2025-02-07 12:35 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +        "temperature", "frequency", "relative_humidity", "expected",
How did you came up with the expected values?

2025-02-11 11:16 UTC, sikersten commented on pyfar/constants/medium_attenuation.py
> +    vapor_com = (0 <= h_water_vapor) & (h_water_vapor <= 100)
What do you think of replacing this with an error message, if the value is outside 0-100?

2025-02-11 11:16 UTC, sikersten commented on pyfar/constants/medium_attenuation.py
> +    vapor_com = (0 <= h_water_vapor) & (h_water_vapor <= 100)
This would also allow removing ``& vapor_com`` everywhere below

2025-02-11 11:16 UTC, sikersten commented on pyfar/constants/medium_attenuation.py
> +    vapor_3_mask = ((0.005 > h_water_vapor)  & vapor_com) | vapor_2_mask
```suggestion
    # molar concentration of water vapour: 0.05% to 5 %
    vapor_1_mask = (0.05 <= h_water_vapor) & (h_water_vapor <= 5) & vapor_com
    # molar concentration of water vapour: 0.005% to 0.05 %, or greater than 5%
    vapor_2_mask = (((0.005 <= h_water_vapor) & (h_water_vapor < 0.05)) | (5 < h_water_vapor)) & vapor_com
    # molar concentration of water vapour: less than 0.005%
    vapor_3_mask = (h_water_vapor < 0.005)  & vapor_com
```

2025-02-11 11:16 UTC, sikersten commented on tests/test_constants_air_attenuation.py
> +    Check alpha after value table in the standard. The accuracy is calculated
```suggestion
    Check alpha after value table in ISO 9613-1. The accuracy is calculated
```

2025-02-12 16:15 UTC, f-brinkmann approved these changes

2025-02-17 07:15 UTC, ahms5 commented on pyfar/constants/speed_of_sound.py
> +def speed_of_sound_ideal_gas(
this file was already reviewed in #739

2025-02-17 11:59 UTC, ahms5 commented
@CristobalAndrade pointed out that ISO Appendix B provides a defined method for calculating saturation vapor pressure. Therefore, I removed the old saturation_vapor_pressure function (still required for ideal gas in #770) and incorporated the calculation directly into the air attenuation function, following the standard's guidelines.

2025-02-18 07:30 UTC, f-brinkmann approved these changes

2025-02-21 06:10 UTC, CristobalAndrade submitted a review, later dismissed

2025-03-28 11:23 UTC, ahms5 commented on tests/test_constants_air_attenuation.py
> +    match = 'Atmospheric pressure must less than 200 kPa.'
```suggestion
    match = 'Atmospheric pressure must be less than 200 kPa.'
```

2025-04-08 12:43 UTC, sikersten requested changes

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +        Atmospheric pressure in pascal, by default
```suggestion
        Atmospheric pressure in Pascal, by default
```

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +        Atmospheric pressure in pascal.
```suggestion
        Atmospheric pressure in Pascal.
```

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +        Saturation vapour pressure in pascal.
```suggestion
        Saturation vapour pressure in Pascal.
```

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +            - frequency-to-pressure ratio: 4 x 10-4 Hz/Pa to 10 Hz/Pa.
Is there an easy solution to put the "-4" as exponent?

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +    m = alpha / (10*np.log10(np.exp(1)))
The documentation states a multiplication instead of division. Is there a reference for this equation?

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +        :math:`m = 10 \cdot \log(\exp(1)) \cdot \alpha`.
Differs from the actual implementation, see below.

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +        Must be lager than 0 Hz.
```suggestion
        Must be larger than 0 Hz.
```

2025-04-08 12:43 UTC, sikersten commented on pyfar/constants/constants.py
> +    """Calculate the accuracy of the air attenuation calculation.
It would make sense to mention the standard somewhere in the docstring

2025-04-08 14:23 UTC, sikersten approved these changes

2025-04-09 08:07 UTC, f-brinkmann approved these changes

2025-04-11 07:08 UTC, mberz requested changes
Only one comment...

.... but why does this PR have 55 commits? 🤣

2025-04-11 07:08 UTC, mberz commented on pyfar/constants/constants.py
> +def _calculate_accuracy(
Accuracy of what? Please be more concise.

2025-04-25 08:32 UTC, mberz approved these changes

2025-04-25 12:36 UTC, merged