Speed of sound after cramer
pyfar/pyfar pull request #738
Opened 2024-12-20 12:24 UTC by ahms5

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +    The conditions are as follows:
```suggestion
    The conditions are as follows:
    
```

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +    - for temperatures from 0°C Cto 30°C
```suggestion
    - temperatures from 0°C to 30°C
```

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +        Atmospheric pressure in pascal, by default 101325 Pa.
```suggestion
        Atmospheric pressure in Pascal, by default 101325 Pa.
```

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +        co2 concentration in parts per million. The default is 315 ppm as a
```suggestion
        CO2 concentration in parts per million. The default is 315 ppm as a
```

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +    - CO2 concentrations up to 10 000 ppm
Maybe add a sentence about the resulting accuracy, see Cramer's abstract?

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +        co2 concentration in parts per million. The default is 315 ppm as a
Why not take Cramer's value of 314 as default (Table I)?

2025-02-07 12:49 UTC, sikersten commented on pyfar/constants/speed_of_sound.py
> +    The conditions are as follows:
It might make sense to restrict the input to these ranges, wouldn't it?

2025-02-12 16:12 UTC, f-brinkmann requested changes
Thanks for the effort. I only suggested a simple additional test for improved robustness. otherwise all good for me.

2025-02-13 06:55 UTC, f-brinkmann approved these changes
Thanks

2025-02-17 12:11 UTC, ahms5 commented
replaced by #771

2025-02-17 12:11 UTC, closed without merging