speed of sound ideal gas law
pyfar/pyfar pull request #739
Opened 2024-12-27 10:11 UTC by ahms5

2025-01-11 21:51 UTC, ahms5 commented on pyfar/constants/speed_of_sound.py
> +        It must be between ?? to ?? Pa.
```suggestion
```

2025-01-23 13:04 UTC, f-brinkmann requested changes
Looks good - I only had small suggestions

2025-01-23 13:04 UTC, f-brinkmann commented on pyfar/constants/speed_of_sound.py
> +    R_a = R/mu_a
```suggestion
    R_a = R / mu_a
```

2025-01-23 13:04 UTC, f-brinkmann commented on tests/test_constants_speed_of_sound.py
Can you please add short docstrings to the tests?

2025-01-23 13:04 UTC, f-brinkmann commented on tests/test_constants_speed_of_sound.py
> +    expected = 343.2*np.sqrt((temperature+273.15)/293.15)
This is used quite often. Maybe put it into a private function and briefly explain where it is coming from to make the tests easier to understand

2025-01-23 13:35 UTC, f-brinkmann approved these changes
Only found one typo. Can you maybe add short docstrings to the tests? Would make stuff easier to maintain. But already approved...

2025-01-23 13:35 UTC, f-brinkmann commented on tests/test_constants_speed_of_sound.py
> +    results are with a senseful range.
```suggestion
    results are within a reasonable range.
```

2025-01-27 11:45 UTC, hoyer-a requested changes
Thanks, just minor comments.

2025-02-07 11:56 UTC, ahms5 commented on tests/test_constants_speed_of_sound.py
> +def _simplified_ideal_gas(temperature):
I did not wanted to check one vs the other method directly, because it does not feel like good practice. Therefore I have added a function just for testing

2025-02-11 09:59 UTC, hoyer-a approved these changes

2025-02-14 13:47 UTC, merged