hot: fix radius check in find_within
pyfar/pyfar pull request #742
Opened 2024-12-27 12:34 UTC by ahms5

2025-01-06 09:51 UTC, hoyer-a reviewed
Thanks! Just one thing.

2025-01-06 09:51 UTC, hoyer-a commented on tests/test_coordinates_find.py
```suggestion
    find.radius = .1
    radius_tol = 0.1
    match = 'find_within only works if all points have the same radius. '
            f'Differences are larger than {radius_tol}'
    with pytest.raises(ValueError, match=match):
        coords.find_within(
            find, distance_measure='spherical_radians', radius_tol=radius_tol)


```

2025-01-06 10:10 UTC, hoyer-a approved these changes

2025-02-04 19:04 UTC, f-brinkmann requested changes
Thanks, I suggest a change for improving the robustness. Otherwise approved.

2025-02-04 19:04 UTC, f-brinkmann commented on pyfar/classes/coordinates.py
> +            radius = np.concatenate((self.radius, find.radius))
There could be cases where this fails. Using this should be safe

```suggestion
            radius = np.concatenate((self.radius.flatten(), find.radius.flatten()))
```

2025-02-07 11:53 UTC, ahms5 commented on pyfar/classes/coordinates.py
> +            radius = np.concatenate((self.radius, find.radius))
Ive also changed it in find_nearest

2025-02-07 12:38 UTC, f-brinkmann approved these changes

2025-02-14 13:48 UTC, merged